# baseURL
@baseURL = http://localhost:3000

###
# User Signup
POST {{ baseURL }}/signup
Content-Type: application/json

{
    "email": "example@email.com",
	"password": "password"
}

###
# User Login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "minhnqnde160634@fpt.edu.vn",
	"password": "Minh0914121791"
}

###
# User Logout
POST {{ baseURL }}/logout
Content-Type: application/json
